### ISSUE TITLE
翻译反馈

### ISSUE THREAD

**Issue by wsxy162** [lmy441900/peazip-l10n-zh-cn#1]
搜索peazip的本地化到了这里，6.4 的版本也是由你更新的，所以在这里讨论下 peazip 的一些汉化问题。

lang-wincontext 下的汉化文件（简体）编码有问题，这里我有一份修改的版本。
[chs.zip](https://github.com/lmy441900/peazip-l10n-zh-cn/files/1668600/chs.zip)
这里我修改了原来的一些翻译。当是使用这个注册文件，右键菜单里的“发送到”子菜单文字还是没汉化。

本来是想顺手翻译下程序本地部分的，但是有些词语翻译不统一，所以停下来发了这个 issue。
比如 archive 这个词，用得最多的翻译是压缩文件和压缩文档，而如果从严格意义上讲，archive 就是个打包文件，压缩与不压缩都可以，常见的格式有 .tar。这么定义的话 archive 的翻译不该包含压缩这个词，更合理的翻译是存档或档案。如果不讲究，随大流点，那原来的翻译也需要统一一下。

**Comment by lmy441900** [comment]
@wsxy162 

> 搜索peazip的本地化到了这里，6.4 的版本也是由你更新的，所以在这里讨论下 peazip 的一些汉化问题。

很抱歉我也有一段时间没关注这块了，今天启动了万年没开的 Windows，顺手更新到了 6.5，才看到这个 Issue（看来我之前点 Mark as read 太随便了）。

> lang-wincontext 下的汉化文件（简体）编码有问题，这里我有一份修改的版本。
> [chs.zip](https://github.com/lmy441900/peazip-l10n-zh-cn/files/1668600/chs.zip)

我也注意到了，95983694b3af7932c7ddd04ffa38c068753b3bd8 已修复，稍后会反馈给作者。

> 这里我修改了原来的一些翻译。当是使用这个注册文件，右键菜单里的“发送到”子菜单文字还是没汉化。

我会看一下，非常感谢。

> 本来是想顺手翻译下程序本地部分的，但是有些词语翻译不统一，所以停下来发了这个 issue。
> 比如 archive 这个词，用得最多的翻译是压缩文件和压缩文档，而如果从严格意义上讲，archive 就是个打包文件，压缩与不压缩都可以，常见的格式有 .tar。这么定义的话 archive 的翻译不该包含压缩这个词，更合理的翻译是存档或档案。如果不讲究，随大流点，那原来的翻译也需要统一一下。

这个翻译我不是从头做起的，一开始 Aerowolf（翻译文件中有写）就已经翻译了一大半，那份翻译也有诸多标点、用词不规范、不统一问题，我只是粗略地改了一些我发现的问题，没有完整阅读这份翻译，所以也没有刻意更改用词。之前一段时间还想着以后有时间就把翻译审阅一遍，结果都没有做（摔）。

用词我会找时间再仔细审阅，当然我首先会看一下你的修改（如果是 PR 就方便多了（笑））。

**Comment by wsxy162** [comment]
啊，我记得了，archive 还可以翻译成归档。新的字符串没添加多少，就是要审查下全部翻译。因为看到用词不统一，就搁笔（键盘）了。

**Comment by lmy441900** [comment]
> archive 还可以翻译成归档

@wsxy162 f2d94309f9 中我参照 Engrampa 的简中翻译，将“压缩文件”和“压缩文档”程序替换成了“归档文件”，您如果有时间的话不妨帮忙看看有没有替换错误。

> 就是要审查下全部翻译

在 f1b6e887bd 中我重新审阅了 PeaLauncher 的翻译（因为字串较少）。我粗略看了一下，主程序有接近一千条字串，做一次完整的审阅应该需要不少时间。我很少有机会抽出大片时间做这个工作，如果您可以参与协作的话会更好。

~~我竟然咕了两年，咳~~

**Comment by wsxy162** [comment]
好的，我可以帮忙核对。完成了再上传到这里。

**Comment by lmy441900** [comment]
@wsxy162 PeaZip 7.2 已经发布，我在 master 的基础上更新了 7.2.z 的翻译，并顺手将“压缩”二字根据原文替换为“归档”（只有原文为 "archive" 的词语被更改为“归档”），请同步更改。

**Comment by wsxy162** [comment]
嗯，好的。我整理好帮助和PeaLaunch，在检查主程序的部分。这个程序翻译不怎么友好，字符串很多是按字母顺序排列的，不好寻找对应界面的归属位置。

**Comment by wsxy162** [comment]
#2 
抱歉拖了很久。这个 PR 你看下，觉得合理的修改可以合并上去。另外我还想改动 Extract 的翻译，把一些翻译从“解压”改成“提取”。

**Comment by lmy441900** [comment]
> 把一些翻译从“解压”改成“提取”

可。

**Comment by lmy441900** [comment]
#2 已合并，做得非常仔细。另 @wsxy162 我已添加你为协作者，你可以直接推送到本仓库。由于作者 Giorgio Tani 目前看起来还只接受邮件更新翻译文件，所以我每次给 Tani 发邮件的时候都打了个 Tag，一般是新 PeaZip 翻译需要更新的时候。如果你认为某个时间点的翻译文件需要给 Tani 合并到软件中，你也可以打个 Tag，并且给 giorgio.tani.software@gmail.com 写封邮件发过去。

**Comment by lmy441900** [comment]
所以 @giorgiotani 既然都在 GitHub 上开仓库了为什么不传代码上来呢，真搞不懂 \~\\_( "/ )\_/~
